-- =============================================================================
-- ReleaseMatch Cloudflare D1 — download_resources 表（兼容入口）
-- =============================================================================
-- 注意：完整线上模型已迁移至 d1_schema.sql（7 张表 + 索引）。
-- 本文件仅保留早期单表引用，避免破坏已有文档链接。
-- 新部署请执行：
--   wrangler d1 execute releasematch --file=schema/d1_schema.sql
--   wrangler d1 execute releasematch --file=schema/d1_seed_demo.sql
-- =============================================================================

-- 见 schema/d1_schema.sql 第 4 节 download_resources 定义
